language: csharp
os:
    - linux
arch:
    - amd64
    - arm64
solution: blazor-test.sln
mono: none
dotnet: 3.1.108
script:
    - dotnet restore
    - dotnet build
deploy:
    provider: azure_web_apps
    edge: true
    skip_cleanup: true
    on:
        branch: main